# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea8461830fe34113e0e93c126ddcc67a3b124de95d7f8af4a76f9d149a0986cadde5d0ab674f3cb8fb81ba149ee320305a5d4a0573dba1cf740816cf65735b6d

test:
  secret_key_base: a78c716ce5512b212fa2f9f5d8f3880079529a2ae76e42f20627c078156466347902a1853ed81573b063fa91ed4068a83f639c72d0809be3556f2942c6866e4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
